apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: p7777
      protocol: TCP
      port: 7777
      targetPort: 7777
  selector:
    app.kubernetes.io/component: pmm-server
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: pmm
    app.kubernetes.io/part-of: percona-platform
  type: LoadBalancer
  loadBalancerIP: 172.23.169.239
  externalTrafficPolicy: Cluster

